{
  nc: 20,
  depth_multiple: 1.0,
  width_multiple: 1.0,
  anchors:
    &id001 [
      [12, 16, 19, 36, 40, 28],
      [36, 75, 76, 55, 72, 146],
      [142, 110, 192, 243, 459, 401],
    ],
  search_space:
    {
      ELAN_Search:
        { gamma_space: [0.75, 1.0, 1.25], connection_space: [0, 1, 2, 3, 4] },
      ELAN2_Search:
        { gamma_space: [0.75, 1.0, 1.25], connection_space: [0, 1, 2, 3, 4] },
    },
  backbone:
    [
      [-1, 1, Conv, [32, 3, 1]],
      [-1, 1, Conv, [64, 3, 2]],
      [-1, 1, Conv, [64, 3, 1]],
      [-1, 1, Conv, [128, 3, 2]],
      [-1, 1, ELAN, [256, 48, [0, 1, 2, 3, 4]]],
      [-1, 1, MP, []],
      [-1, 1, Conv, [128, 1, 1]],
      [-3, 1, Conv, [128, 1, 1]],
      [-1, 1, Conv, [128, 3, 2]],
      [[-1, -3], 1, Concat, [1]],
      [-1, 1, ELAN, [512, 96, [0, 1, 2, 3, 4]]],
      [-1, 1, MP, []],
      [-1, 1, Conv, [256, 1, 1]],
      [-3, 1, Conv, [256, 1, 1]],
      [-1, 1, Conv, [256, 3, 2]],
      [[-1, -3], 1, Concat, [1]],
      [-1, 1, ELAN, [1024, 192, [0, 1, 2, 3, 4]]],
      [-1, 1, MP, []],
      [-1, 1, Conv, [512, 1, 1]],
      [-3, 1, Conv, [512, 1, 1]],
      [-1, 1, Conv, [512, 3, 2]],
      [[-1, -3], 1, Concat, [1]],
      [-1, 1, ELAN, [1024, 320, [0, 1, 2, 3, 4]]],
    ],
  head:
    [
      [-1, 1, SPPCSPC, [512]],
      [-1, 1, Conv, [256, 1, 1]],
      [-1, 1, nn.Upsample, [null, 2, nearest]],
      [16, 1, Conv, [256, 1, 1]],
      [[-1, -2], 1, Concat, [1]],
      [-1, 1, ELAN2, [256, 128, [0, 1, 2, 3, 4]]],
      [-1, 1, Conv, [128, 1, 1]],
      [-1, 1, nn.Upsample, [null, 2, nearest]],
      [10, 1, Conv, [128, 1, 1]],
      [[-1, -2], 1, Concat, [1]],
      [-1, 1, ELAN2, [128, 64, [0, 1, 2, 3, 4]]],
      [-1, 1, MP, []],
      [-1, 1, Conv, [128, 1, 1]],
      [-3, 1, Conv, [128, 1, 1]],
      [-1, 1, Conv, [128, 3, 2]],
      [[-1, -3, 28], 1, Concat, [1]],
      [-1, 1, ELAN2, [256, 160, [0, 1, 2, 3, 4]]],
      [-1, 1, MP, []],
      [-1, 1, Conv, [256, 1, 1]],
      [-3, 1, Conv, [256, 1, 1]],
      [-1, 1, Conv, [256, 3, 2]],
      [[-1, -3, 23], 1, Concat, [1]],
      [-1, 1, ELAN2, [512, 256, [0, 1, 2, 3, 4]]],
      [33, 1, RepConv, [256, 3, 1]],
      [39, 1, RepConv, [512, 3, 1]],
      [45, 1, RepConv, [1024, 3, 1]],
      [[46, 47, 48], 1, IDetect, [20, *id001]],
    ],
  csp_gammas: [0.75, 0.75, 0.75, 1.25, 1.0, 1.0, 1.25, 1.0],
}
