# parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [13,17,  31,25,  24,51, 61,45]  # P3/8
  - [48,102,  119,96, 97,189, 217,184]  # P4/16
  - [171,384, 324,451, 616,618, 800,800]  # P5/32

search_space:
  BottleneckCSP_Search:
    gamma_space: &id001 [0.25, 0.50, 0.75]
    bottleneck_space: &id002 [1,3,7,11]

  BottleneckCSP2_Search:
    gamma_space: &id003 [0.25, 0.50, 0.75]
    bottleneck_space: &id004 [1,3,5,7]

# csp-p5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [32, 3, 1]],  # 0
   [-1, 1, Conv, [64, 3, 2]],  # 1-P1/2
   [-1, -1, BottleneckCSP_Search, [64]],
   [-1, 1, Conv, [128, 3, 2]],  # 3-P2/4
   [-1, -1, BottleneckCSP_Search, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 5-P3/8
   [-1, -1, BottleneckCSP_Search, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 7-P4/16
   [-1, -1, BottleneckCSP_Search, [512]],
   [-1, 1, Conv, [1024, 3, 2]], # 9-P5/32
   [-1, -1, BottleneckCSP_Search, [1024]],  # 10
  ]

# yolov4-p5 head
# na = len(anchors[0])
head:
  [[-1, 1, SPPCSP, [512]], # 11
   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, Upsample, [None, 2, 'nearest']],
   [8, 1, Conv, [256, 1, 1]], # route backbone P4
   [[-1, -2], 1, Concat, [1]],
   [-1, -1, BottleneckCSP2_Search, [256]], # 16 
   [-1, 1, Conv, [128, 1, 1]],
   [-1, 1, Upsample, [None, 2, 'nearest']],
   [6, 1, Conv, [128, 1, 1]], # route backbone P3
   [[-1, -2], 1, Concat, [1]],
   [-1, -1, BottleneckCSP2_Search, [128]], # 21
   [-1, 1, Conv, [256, 3, 1]],
   [-2, 1, Conv, [256, 3, 2]],
   [[-1, 16], 1, Concat, [1]],  # cat
   [-1, -1, BottleneckCSP2_Search, [256]], # 25
   [-1, 1, Conv, [512, 3, 1]],
   [-2, 1, Conv, [512, 3, 2]],
   [[-1, 11], 1, Concat, [1]],  # cat
   [-1, -1, BottleneckCSP2_Search, [512]], # 29
   [-1, 1, Conv, [1024, 3, 1]],

   [[22,26,30], 1, Detect, [nc, anchors]],   # Detect(P3, P4, P5)
  ]