{nc: 80, depth_multiple: 1.0, width_multiple: 1.0, anchors: &id001 [[12, 16, 19, 36,
      40, 28], [36, 75, 76, 55, 72, 146], [142, 110, 192, 243, 459, 401]], search_space: {
    ELAN_Search: {gamma_space: [0.75, 1.0, 1.25], connection_space: [-1, -2, -3, -4,
        -5, -6]}, ELAN2_Search: {gamma_space: [0.75, 1.0, 1.25], connection_space: [
        -1, -2, -3, -4, -5, -6]}}, backbone: [[-1, 1, Conv, [32, 3, 1]], [-1, 1, Conv,
      [64, 3, 2]], [-1, 1, Conv, [64, 3, 1]], [-1, 1, Conv, [128, 3, 2]], [-1, 1,
      ELAN, [256, 80, [-2, -3, -6, -7, -8], 8]], [-1, 1, MP, []], [-1, 1, Conv, [
        128, 1, 1]], [-3, 1, Conv, [128, 1, 1]], [-1, 1, Conv, [128, 3, 2]], [[-1,
        -3], 1, Concat, [1]], [-1, 1, ELAN, [512, 96, [-3, -4, -5, -6, -7, -8], 8]],
    [-1, 1, MP, []], [-1, 1, Conv, [256, 1, 1]], [-3, 1, Conv, [256, 1, 1]], [-1,
      1, Conv, [256, 3, 2]], [[-1, -3], 1, Concat, [1]], [-1, 1, ELAN, [1024, 192,
        [-1, -2, -5, -6, -7], 7]], [-1, 1, MP, []], [-1, 1, Conv, [512, 1, 1]], [
      -3, 1, Conv, [512, 1, 1]], [-1, 1, Conv, [512, 3, 2]], [[-1, -3], 1, Concat,
      [1]], [-1, 1, ELAN, [1024, 320, [-1, -2, -3, -4, -5, -6, -7], 7]]], head: [
    [-1, 1, SPPCSPC, [512]], [-1, 1, Conv, [256, 1, 1]], [-1, 1, nn.nn.Upsample, [null,
        2, nearest]], [16, 1, Conv, [256, 1, 1]], [[-1, -2], 1, Concat, [1]], [-1,
      1, ELAN2, [256, 160, [-1, -2, -3, -5, -6, -7, -8], 8]], [-1, 1, Conv, [128,
        1, 1]], [-1, 1, nn.nn.Upsample, [null, 2, nearest]], [10, 1, Conv, [128, 1, 1]],
    [[-1, -2], 1, Concat, [1]], [-1, 1, ELAN2, [128, 80, [-3, -5, -6, -7, -8], 8]],
    [-1, 1, MP, []], [-1, 1, Conv, [128, 1, 1]], [-3, 1, Conv, [128, 1, 1]], [-1,
      1, Conv, [128, 3, 2]], [[-1, -3, 28], 1, Concat, [1]], [-1, 1, ELAN2, [256,
        96, [-1, -2, -4, -5, -6, -7, -8], 8]], [-1, 1, MP, []], [-1, 1, Conv, [256,
        1, 1]], [-3, 1, Conv, [256, 1, 1]], [-1, 1, Conv, [256, 3, 2]], [[-1, -3,
        23], 1, Concat, [1]], [-1, 1, ELAN2, [512, 192, [-2, -3, -4, -6, -7, -8],
        8]], [33, 1, RepConv, [256, 3, 1]], [39, 1, RepConv, [512, 3, 1]], [45, 1,
      RepConv, [1024, 3, 1]], [[46, 47, 48], 1, IDetect, [80, *id001, [256, 512, 1024]]]],
  csp_gammas: [1.25, 0.75, 0.75, 1.25, 1.25, 1.25, 0.75, 0.75]}
